services:
  - type: web
    name: bulk-mail-app
    env: node
    buildCommand: npm install && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: node backend/index.js
    envVars:
      - key: NODE_ENV
        value: production
