services:
  - type: web
    name: bulk-mail-app
    env: node
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
