services:
  - type: web
    name: bulk-mail-app
    runtime: node
    buildCommand: npm ci && npm ci --prefix frontend && npm run build --prefix frontend
    startCommand: node backend/index.js
    envVars:
      - key: NODE_ENV
        value: production
